class AddClientIdToExpenses < ActiveRecord::Migration[6.1]
  # Idempotency key generated by the iOS client. Allows POST /expenses to be
  # retry-safe under offline-queue replay, network timeouts, and crashed syncs.
  # Two creates with the same (user_id, client_id) collapse into one row.
  def change
    add_column :expenses, :client_id, :string

    # Partial unique index — existing rows have NULL client_id and stay valid.
    add_index :expenses, [:user_id, :client_id],
              unique: true,
              where: "client_id IS NOT NULL",
              name: "index_expenses_on_user_id_and_client_id"
  end
end
